language: node_js
node_js:
- '8'
before_deploy: npm install -g now
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
env:
  global:
    secure: R4B+LMCmTnnrj9UGwc6yFX5VsU3bg1tOys3fqvVp7/KBluXjFapiewlhUIyvMIJjMPv4wzCaezMDGFmRiVy8WTpIhE9p8HmpTuESxByg0VjvHafSSXprDdzvRA69j8RxqGjM+ZuVdsSap4U/2NOfxoKdnJhGJdOcAg36DatNgX+TU5fQ2XMqoyds5mCsZCRBIFPwy2FuD4DDfnXrgM6XpFgniwDc9n+ueJy9TgYLXOvQ6akNHrTOBt082CSiV00t8l/bejpiikQnCTcpS87ArUscW0F2Q+4xcv0fzLG176OqPDDraw3ua9U6c4LxP2yncr0DvLBZ0FdfRu49gqi9+ooPvQgIWR3Tk7B0H8X6Jkb4U7SFI9QHDq+xW+y2jp0FTDIjhOn8p8ko4ZuQQS0nymkmcy4E0AWqDKkLZIkUKYJCH9jrXmYRKtGMxPgZNaj7FkDaw1d9zT7Nv4FwS5EwSQjtEUE9MzW7i0lcPB6HhY2axSgUvIFYsJEzFDPZIMRIUrAH+DdqfH+U4aeHL7RZlXpZ3by1NQ7UKsKnz8EQZeRBsWezCJKuxkp3KD5ONI3ncI4+WZPPIxcVr7/knrFw03fjJWE0/+sMJOuUrtTEqx2pdIFhfF7L5Dfbs2wUWP/b3RNIJsYmkCs4d+3GNDPOuABXsbu5PJtHTnL3Gt4KILg=
